### ISSUE TITLE
Can't find env AcrobotContinuousVisionX-v0

### ISSUE THREAD

**Issue by linshiyx** [tpbarron/imle#1]
I do `pip install gym[all]` and there's no AcrobotContinuousVisionX-v0 or HalfCheetahVisionBulletX-v0

**Comment by tpbarron** [comment]
Those tasks are in Pybullet not Mujoco and aren't integrated with the main gym package. You need to add my gym-x package  to your pythonpath https://github.com/tpbarron/gym-x. Then they should be accessible but you should check the code for the HalfCheetahVision envs since I haven't tried them recently.

**Comment by linshiyx** [comment]
It worked. Thank you.
